### PR TITLE
Update ripple.android.ts

### PR DESCRIPTION
**Pull request by jgraffite**

### CODE REVIEW

**Comment by bradmartin** [comment]
@jgraffite - all working on android and iOS here? Haven't had time to go through and review all the changes yet. Let me know if it's ready and I'll do a quick test and publish for the update.

Thanks 😄

**Comment by jgraffite** [comment]
Hi Martin,

All working in both Android and iOS.

Some hours ago, I tested in a iOS emulator to be sure that that's working out. After that, I commited the latest modifications


Obs.: Sorry for my poor English :D

**Comment by jgraffite** [comment]
Hi @bradmartin ,

All working in both Android and iOS.

Some hours ago, I tested in a iOS emulator to be sure that that's working out. After that, I commited the latest modifications

Obs.: Sorry for my poor English :D

**Comment by bradmartin** [comment]
Thanks. Your English is fine, better than a lot of native English speaking
people :) I'll review and publish later this week.

CC @jenlooper - swag reward

**Comment by bradmartin** [comment]
@jen.looper

**Comment by bradmartin** [comment]
@jlooper ^^

**Pull request merged**
