### PR TITLE
Issue #9

### PR DESCRIPTION
**Pull request by mn-martin**

### CODE REVIEW

**Review by bradmartin — COMMENTED** [review]
@mn-martin - this work with NS 3.0, correct?

**Comment by cboisen** [comment]
We would really like this to be a part of the plugin (perhaps even on the dev branch for testing). We run tns 3, and would love to disable the plugin on iOS.

On a related note: The "iOS support" is visually off. It doesn't conform with the material design spec, and as such is not useful.

**Comment by mn-martin** [comment]
@hauthorn This was for intended for NS ^2. I didn't had the time to look into this with NS ^3 yet.

**Comment by bradmartin** [comment]
Apologies I let this one slide by. Would either of you two be interested in being added as Collaborators to the repo so you can help maintain it?

@hauthorn @mn-martin 

CC @jgraffite also to see if interested in helping.

**Comment by jgraffite** [comment]
Yes, @bradmartin , I will help to make this functionality (option to disable effect on iOS) to iOS working on NS 3

**Comment by bradmartin** [comment]
Thanks @jgraffite - you are now a collaborator on the repo so you can manage it. If anyone else wants to assist just ping me here and let me know.

**Comment by cboisen** [comment]
I can help with this fix if you need me to.

**Comment by bradmartin** [comment]
@hauthorn you're also now a collaborator. Both of you can manage this repository now 👍

**Comment by mn-martin** [comment]
@bradmartin This is my work github account. My private account is: https://github.com/hettiger If you add my private account I'll help as soon as I get the chance to for sure.

**Comment by jogboms** [comment]
Can we continue in this direction 👍

**Pull request closed without merging**
